modelmanager/generator/urls.py
from django.conf.urls import url

from .views import OverviewView, GenerateMetadataWizard


app_name = 'generator'
urlpatterns = [
    url(r'^$', OverviewView.as_view(), name='overview'),
    url(r'^generate/$', GenerateMetadataWizard.as_view(), name='generate')
]

modelmanager/identity/urls.py
from django.conf.urls import url

from .views import LoginView


app_name = 'identity'
urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
]

modelmanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import IndexView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^generator/', include('modelmanager.generator.urls')),
    url(r'^identity/', include('modelmanager.identity.urls')),
]

modelmanager/generator/forms.py
from django import forms


class BootstrapFormMixin(object):

    def __init__(self, *args, **kwargs):
        super(BootstrapFormMixin, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class ContactForm1(BootstrapFormMixin, forms.Form):
    subject = forms.CharField(max_length=100)
    sender = forms.EmailField()


class ContactForm2(BootstrapFormMixin, forms.Form):
    message = forms.CharField(widget=forms.Textarea)

modelmanager/generator/views.py
import logging

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from modelmanager.mixins import LoginRequired

from .forms import ContactForm1, ContactForm2
from .generic_views import GeneratedWizardView

LOG = logging.getLogger(__name__)


class OverviewView(LoginRequired, TemplateView):
    template_name = 'generator/overview.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super(OverviewView, self).get_context_data(*args, **kwargs)

        return ctx


class GenerateMetadataWizard(GeneratedWizardView):
    initial_dict = {
        'contact_form_1': {
            'subject': 'test',
            'sender': 'test@test.cz'
        }
    }
    template_name = 'common/wizard_form.html'

    def done(self, form_list, **kwargs):
        LOG.error('CONTACT WIZARD DONE')
        return HttpResponseRedirect(reverse_lazy('generator:overview'))

modelmanager/views.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

modelmanager/generator/templates/generator/overview.html
{% extends 'common/base.html' %}

{% load i18n %}

{% block title %}
  {% trans "Overview" %}
{% endblock %}

{% block pagetitle %}
  {% trans "Overview" %}
{% endblock %}

{% block head %}
<style>
.table-actions {
  padding-bottom: 20px;
}
</style>
{% endblock %}

{% block content %}
<div class="col-xs-12">
{% if user.is_authenticated %}
  <div class="table-actions text-right">
    <div class="btn-group btn-group-sm">
      <a href="{% url 'generator:generate' %}" class="btn btn-primary">{% trans "Generate Metadata" %}</a>
    </div>
  </div>
{% else %}
  <div class="col-xs-6 col-xs-offset-3">
    <div class="well">
      <p class="text-center">Log in to see your generator.</p>
    </div>
  </div>
{% endif %}
</div>

{% endblock %}

modelmanager/templates/common/_right_nav.html
{% load i18n %}

<li>
  <a style="pointer-events: none;">{{ request.user.email }} / {{ request.user.tenantmembership.tenant }}</a>
</li>
<li class="dropdown">
  <a href="#" data-toggle="dropdown" class="dropdown-toggle">{% trans "Profile" %}<b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
  </ul>
</li>

modelmanager/templates/common/base.html
{% load i18n %}

<!doctype html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, minimum-scale=1.0 minimal-ui"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>

        {% load staticfiles %}
        <link rel="shortcut icon" href="{% static "favicon.ico" %}" />

        <title>{% block title %}{% endblock %}</title>

        <script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.js"></script>
        <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/simplex/bootstrap.min.css">
        <style>
        #main_content {
          margin-top: 81px;
        }
        </style>
        {% block head %}{% endblock %}
    </head>
    <body>
        {% if request.user.is_authenticated %}
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">{% trans "StackView" %}</a>
                    <button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar-main" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                      {% include "common/_right_nav.html" %}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}

        <div id="main_content">
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <div id="banner" class="page-header {% if not request.user.is_authenticated %}col-xs-6 col-xs-offset-3 text-center{% endif %}">
                  <h1>{% block pagetitle %}{% endblock %}</h1>
                </div>
              </div>
              {% if messages %}
                <div class="messages">
                  {% for message in messages %}
		    <div class="alert alert-dismissable {{ message.tags }}">
                      <button type="button" class="close" data-dismiss="alert">×</button>
                      {{ message }}
		    </div>
                  {% endfor %}
                </div>
              {% endif %}

              {% block content %}{% endblock %}

              <div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h4 class="modal-title"></h4>
                    </div>
                    <div id="form-modal-body" class="modal-body">
                    </div>
                    <div class="modal-footer">
                    </div>
                  </div>
                </div>
              </div>

              <script>
              $(document).ready(function() {
                $('a[data-toggle="modal"]').on('click', function(e) {
                  var target_modal = $(e.currentTarget).data('target');
                  var remote_content = e.currentTarget.href;

                  var modal = $(target_modal);
                  var modalBody = $(target_modal + ' .modal-body');
                  var modalTitle = $(target_modal + ' .modal-title');
                  var title = $(e.currentTarget).data('title');

                  modal.on('show.bs.modal', function () {
                          modalBody.load(remote_content);
                          modalTitle.html(title);
                      }).modal();

                  return false;
                });
              });
              </script>
            </div>
          </div>
        </div>
    </body>
</html>

modelmanager/templates/common/modal_base.html
<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{% block modal_title %}{% endblock %}</h4>
      </div>
      <div id="form-modal-body" class="modal-body">
        {% block modal_body %}{% endblock %}
      </div>
      <div class="modal-footer">
        {% block modal_footer %}{% endblock %}
      </div>
    </div>
  </div>
</div>

modelmanager/templates/common/wizard_form.html
{% extends "common/base.html" %}
{% load i18n %}

{% block title %}
  {% trans "Generate Metadata" %}
{% endblock %}

{% block pagetitle %}
  {% trans "Generate Metadata" %}
{% endblock %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block content %}
<div class="col-xs-12">
  <p class="text-center">Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
  <form action="" method="post">{% csrf_token %}
    <table>
      {{ wizard.management_form }}
      {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
          {{ form }}
        {% endfor %}
      {% else %}
        {{ wizard.form }}
      {% endif %}
    </table>
    {% if wizard.steps.prev %}
      <button class="btn btn-secondary" name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
      <button class="btn btn-secondary" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
    {% endif %}
    <input class="btn btn-primary" type="submit" value="{% trans "submit" %}"/>
  </form>
</div>
{% endblock %}

modelmanager/templates/index.html
{% extends 'common/base.html' %}

{% load i18n %}

{% block title %}
  {% trans "Home" %}
{% endblock %}

{% block pagetitle %}
  {% trans "Welcome!" %}
{% endblock %}

{% block head %}
<style>
.gallery {
  margin: 0 auto;
  padding: 5px;
  background: #4e5d6c;
  box-shadow: 0 1px 2px rgba(0,0,0,.3);
}

.gallery > div {
  position: relative;
  float: left;
  padding: 13px;
}

.gallery > div > a > img {
  display: block;
  width: 200px;
  transition: .1s transform;
  transform: translateZ(0); /* hack */
}

.gallery > div:hover {
  z-index: 1;
}

.gallery > div:hover > a:not(.disabled) > img {
  transform: scale(1.2,1.2);
  transition: .3s transform;
}

.gallery > div > a.disabled > img {
  -webkit-filter: grayscale(100%); /* Safari 6.0 - 9.0 */
  filter: grayscale(100%);
}

.cf:before, .cf:after {
  display: table;
  content: "";
  line-height: 0;
}

.cf:after {
  clear: both;
}
</style>
{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
<div class="col-xs-12">
  <div class="gallery cf">
    <div>
      <a href="{% url 'generator:overview' %}">
        <img src="https://vexxhost.com/file/2016/02/Database-Cloud-256.png" />
      </a>
    </div>
    <div>
      <a class="disabled" href="#">
        <img src="https://vexxhost.com/file/2016/02/Database-Cloud-256.png" />
      </a>
    </div>
    <div>
      <a class="disabled" href="#">
        <img src="https://vexxhost.com/file/2016/02/Database-Cloud-256.png" />
      </a>
    </div>
    <div>
      <a class="disabled" href="#">
        <img src="https://vexxhost.com/file/2016/02/Database-Cloud-256.png" />
      </a>
    </div>
    <div>
      <a class="disabled" href="#">
        <img src="https://vexxhost.com/file/2016/02/Database-Cloud-256.png" />
      </a>
    </div>
  </div>
{% else %}
<div class="col-xs-6 col-xs-offset-3">
  <div class="well">
    <p class="text-center">Click <a href="{% url 'identity:login' %}">here</a> to login.</p>
  </div>
</div>
{% endif %}
{% endblock %}